-- Question 1
SELECT COUNT(DISTINCT LAST_NAME) AS LAST_NAME_COUNT
FROM SAKILA.ACTOR

-- Question 2
SELECT DISTINCT LANGUAGE_ID
FROM SAKILA.FILM

-- Question 3
SELECT COUNT(DISTINCT FILM_ID) AS FILM_COUNT
FROM SAKILA.FILM
WHERE RATING = 'PG-13'

-- Question 4
SELECT DISTINCT TITLE
				, LENGTH
FROM SAKILA.FILM
ORDER BY LENGTH DESC
LIMIT 10;

-- Question 5
SELECT DATEDIFF(MAX(RETURN_DATE), MIN(RENTAL_DATE)) AS OPERATING_DAY_COUNT
FROM SAKILA.RENTAL

-- Question 6 and 7
SELECT *
, MONTH(RENTAL_DATE) AS RENTAL_MONTH
, WEEKDAY(RENTAL_DATE) AS RENTAL_WEEK_DAY
, CASE WHEN WEEKDAY(RENTAL_DATE) = 0 THEN 'MONDAY'
		WHEN WEEKDAY(RENTAL_DATE) = 1 THEN 'TUESDAY'
		WHEN WEEKDAY(RENTAL_DATE) = 2 THEN 'WEDNESDAY'
		WHEN WEEKDAY(RENTAL_DATE) = 3 THEN 'THURSDAY'
		WHEN WEEKDAY(RENTAL_DATE) = 4 THEN 'FRIDAY'
		WHEN WEEKDAY(RENTAL_DATE) = 5 THEN 'SATURDAY'
		WHEN WEEKDAY(RENTAL_DATE) = 6 THEN 'SUNDAY' END AS RENTAL_WEEK_DAY_TEXT
, CASE WHEN WEEKDAY(RENTAL_DATE) IN (0,1,2,3,4) THEN 'WORKDAY' ELSE 'WEEKEND' END AS DAY_TYPE
FROM SAKILA.RENTAL
LIMIT 20;

-- Question 8 
SELECT DISTINCT DATE_FORMAT(RENTAL_DATE, '%Y-%m') AS YEAR_MONTH_DATE
, COUNT(DISTINCT RENTAL_ID) AS RENTAL_COUNT
FROM SAKILA.RENTAL
GROUP BY 1
ORDER BY YEAR_MONTH_DATE DESC
LIMIT 1;